### PR TITLE
Add validation of reactions

### LINKED ISSUE #6: Add SMARTS validation
TO DO:

- add validation function for SMARTS/CXSMARTS
- unit test on examples

### PR DESCRIPTION
**Pull request by Adafede**
@mmzdouc Implementation is still TODO, but most pieces should be there. I added the tests I could think of but they for sure do not cover anough cases

Fixes #6

### CODE REVIEW

**Comment by mmzdouc** [comment]
Suggestions:

- [ ] "canonicalize" reaction SMARTS by removing numbering (if not needed), converting into aromatic version

**Comment by mmzdouc** [comment]
Intermediate update: https://github.com/mite-standard/mite_extras/pull/23
I compared the branches and at the moment all looks good, but this could lead to potential merge conflicts - cave

**Comment by Adafede** [comment]
@mmzdouc I'll try to implement what we discussed later but for now I added a small `has_cx_layer` check to canonicalize only when there is no CX layer. It was needed to fix some tests.

**Comment by Adafede** [comment]
@mmzdouc Loosing my head on this one...it still fails because RDKit produces an invalid structure after reaction... 😢

**Comment by mmzdouc** [comment]
> @mmzdouc Loosing my head on this one...it still fails because RDKit produces an invalid structure after reaction... 😢

@Adafede which one exactly? Is it one of the ones I sent you? Perhaps I made an error?

**Comment by Adafede** [comment]
Ok... quite disappointed I could not implement an alternative enumeration properly...

@mmzdouc , @daenuprobst if you got any idea... very welcome!

- [ ] I had to "hack" a pseudo internal reaction for composite reactions, adding parenthesis for it to work with RDKit
- [ ] Enumeration of CX-layered reactants and products works but somehow not in a reaction object... I'll need to investigate

**Comment by Adafede** [comment]
@mmzdouc I would say it can be used for now, what do you think?

**Comment by Adafede** [comment]
@mmzdouc Implemented frequency variation! 🥳 (and forbidden products test)

**Comment by Adafede** [comment]
@mmzdouc Should be ready now!

**Review by mmzdouc — APPROVED** [review]
Looks good, great job!

**Pull request merged**
